---
- name: Create a NS
  hosts: localhost 
  tasks:
   - name: Create a k8s namespace
     kubernetes.core.k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present
  
